name: Close Pull Request

on:
  pull_request_target:
    types: [opened]
    paths: README.md

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Closing for a new session!"
