name: Close inactive issues
on:
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          days-before-issue-close: 10
          stale-issue-label: "stale"
          close-issue-message: "This issue was closed because it has been inactive for 10 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
